### ISSUE TITLE
feature: disable proxy

### ISSUE THREAD

**Issue by Sispheor** [ruzickap/ansible-role-proxy_settings#2]
It would be nice to have a method to perform the opposite action. I mean disabling the proxy.

If we want to disable the proxy (like a roolback) we can play back the role with each settings set to an empty value. The problem is that would let unused variables into the env. Furthermore, some programs can be disturbed by the fact that the variable exist but it's empty.

I have this in mind because I'm working on a cloud image preparation where I have to add the proxy in order to install packages that I want in my image and then remove the proxy to offer a cleaned image.

**Comment by JamesHutchinsonHV** [comment]
I have the same requirement, I use this role during the server build process to deploy packages in one location and then need to remove the proxy settings before the VM is exported to an OVA ready for use on customer site.  As per @Sispheor I'm not sure setting empty vars is a good solution, I would rather remove the configuration from the files.

**Comment by Sispheor** [comment]
I've started [a project](https://github.com/Sispheor/ansible-role-workstation-env-switcher) a couple time ago.
Maybe need to be updated a bit. But it allow to "switch" environment.
I use this to switch my full workstation env from home config to work config (DNS, proxy, ntp,...)
